### PR TITLE
 feat(cli): add release cli

### PR DESCRIPTION
**Pull request by kdada**
**What this PR does / why we need it**:

Add release cli.
This command can help to check chart and `values.yaml`. 

```
Useful tools for release

Usage:
  release-cli [command]

Available Commands:
  get         Get a release from kubernetes cluster
  help        Help about any command
  lint        Lint checks if a chart is right
  list        List releases from a kubernetes cluster

Flags:
      --alsologtostderr                  log to standard error as well as files
  -h, --help                             help for release-cli
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory
      --logtostderr                      log to standard error instead of files (default true)
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          log level for V logs
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

Use "release-cli [command] --help" for more information about a command.

```

**Which issue(s) this PR fixes** *(optional, close the issue(s) when PR gets merged)*:

Fixes #

**Special notes for your reviewer**:

/cc @zoumo 
/cc @supereagle 
/cc @bbbmj 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by kdada** [comment]
/approve cancel 
@zoumo  This repo should be renamed.

**Comment by supereagle** [comment]
> @zoumo This repo should be renamed.

How is this repo renamed? A little strange ...

**Comment by supereagle** [comment]
> @zoumo This repo should be renamed.

release-controller is renamed to rudder, xref: https://github.com/caicloud/tools/pull/255#discussion_r181608782

**Pull request merged**
